name: passline
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  items_repository:
    path: items_repository
  user_repository:
    path: user_repository
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.1
  equatable: ^0.6.0
  password_hash: ^2.0.0
  cryptography: ^1.4.1
  local_auth: ^0.6.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter 